INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Иванов', 'Иван', 'мастер-приемщик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Петров', 'Василий', 'кузовщик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Сидоров', 'Сергей', 'электрик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Иванов', 'Алексей', 'кузовщик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Спиридонов', 'Вадим', 'мастер общего профиля');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Ершов', 'Александр', 'электрик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Петров', 'Матвей', 'моторист');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Иванов', 'Сергей', 'кузовщик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Дудкин', 'Иван', 'мастер общего профиля');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Матвеев', 'Пётр', 'моторист');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Пушкин', 'Даниил', 'мастер-приемщик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Семёнов', 'Дмитрий', 'мастер-приемщик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Туркин', 'Дмитрий', 'кузовщик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Огурцов', 'Сергей', 'электрик');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Сергеев', 'Валентин', 'мастер общего профиля');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Лосева', 'Ирина', 'моторист');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Петрова', 'Татьяна', 'моторист');
INSERT INTO public.employees(first_name, last_name, job_position)	VALUES ('Иванова', 'Лариса', 'мастер общего профиля');

INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Замена ГРМ:ролики',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Замена ГРМ:ремень',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Ремонт головки и блока цилиндров:кольца',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Ремонт головки и блока цилиндров:цилиндры',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Ремонт головки и блока цилиндров:клапана',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Ремонт коленчатого вала:вкладыши коленвала',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Ремонт коленчатого вала:вкладыши шатуна',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Ремонт охлаждения:термостат',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Ремонт охлаждения:замена радиатора',1500);
INSERT INTO public.items_price(item, price)	VALUES ('неисправность ДВС:Ремонт охлаждения:замена вентилятора',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт рулевого:рулевая рейка',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт рулевого:гидроусилитель руля',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт задней подвески:Пружины',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт задней подвески:Амортизаторы',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт передней подвески:Пружины',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт передней подвески:Амортизаторы',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт передней подвески:Рычаги',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт заднего привода:дифференциал',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт заднего привода:полуоси',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт заднего привода:кардан',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт переднего привода:ШРУСы',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Неисправность ходовой и подвески:Ремонт переднего привода:Промвалы',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Стапельные работы:замена кузовного элемента',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Покраска',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Рихтовка',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Левый лонжерон',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:правый лонжерон',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Капот',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Багажник',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Бампер передний',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Бампер задний',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Крыло левое',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Крыло правое',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Фара левая',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Фара правая',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Фонарь левый',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Фонарь правый',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Пороги',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Кузовной ремонт:Замена кузовного элемента:Крыша',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Электрика автомобиля:Датчики:давления масла двигателя',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Электрика автомобиля:Датчики:температуры двигателя',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Электрика автомобиля:Датчики:оборотов двигателя',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Электрика автомобиля:Датчики:скорости',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Электрика автомобиля:Свечи',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Электрика автомобиля:Внутренняя электрика',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Электрика автомобиля:Предохранители',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Электрика автомобиля:ЭБУ',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Система подачи топлива:Карбюратор',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Система подачи топлива:Инжектор',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Топливная система:Топливный бак',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Топливная система:Топливная магистраль',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Топливная система:Топливный насос',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Механическая коробка передач:диск сцепления',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Механическая коробка передач:выжимной подшипник',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Механическая коробка передач:корзина сцепления',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Автоматическая коробка передач:фрикционные диски',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Автоматическая коробка передач:гидроблок',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Автоматическая коробка передач:гидротрансформатор',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Ремонт тормозной системы:Главный цилиндр',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Ремонт тормозной системы:Тормозной суппорт/цилиндр барабанов',1500);
INSERT INTO public.items_price(item, price)	VALUES ('Ремонт тормозной системы:Тормозная магистраль',1500);


